baseURL = "https://okolotattoo.netlify.app/"
languageCode = "ru"
defaultContentLanguage = "en"

title = "Околотату"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Околотату"
  headline = "Подпишись"
  image = "/img/author.png"
  favicon = "/favicon.ico"

  links = [
    { telegram = "https://t.me/nononotattoo" },
    { group = { href = "https://t.me/+S_Qp2P_zsaz983_x", text = "Чат" } },
    { youtube = "https://www.youtube.com/@okolotattooing" },
    { instagram = "https://www.instagram.com/okolotattooing" },
    { group = { href = "https://vk.com/okolotattoo", text = "Vk" } },
          ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"