[build]
  command = "hugo --gc --minify -D -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.142.0"
  
[context.production.environment]
  HUGO_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-hugo"
